version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data
    restart: always
  dnmonster:
    image: amouat/dnmonster:latest
    container_name: dnmonster
    ports:
    - "8080:8080"
    restart: always
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python
    ports:
      - "8888:8888"
    restart: always
    links:
      - redis
      - dnmonster
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    links:
      - backend
    ports:
    - "8880:8880"
